/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVariableRouteImport } from './routes/_authenticated/variable'
import { Route as AuthenticatedShiftRouteImport } from './routes/_authenticated/shift'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductivityRouteImport } from './routes/_authenticated/productivity'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLeaderRankingRouteImport } from './routes/_authenticated/leader-ranking'
import { Route as AuthenticatedLeaderProceduresRouteImport } from './routes/_authenticated/leader-procedures'
import { Route as AuthenticatedLeaderMapRouteImport } from './routes/_authenticated/leader-map'
import { Route as AuthenticatedLeaderConfigRouteImport } from './routes/_authenticated/leader-config'
import { Route as AuthenticatedLeaderRouteImport } from './routes/_authenticated/leader'
import { Route as AuthenticatedShiftIdReportRouteImport } from './routes/_authenticated/shift_.$id.report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVariableRoute = AuthenticatedVariableRouteImport.update({
  id: '/variable',
  path: '/variable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftRoute = AuthenticatedShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductivityRoute =
  AuthenticatedProductivityRouteImport.update({
    id: '/productivity',
    path: '/productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderRankingRoute =
  AuthenticatedLeaderRankingRouteImport.update({
    id: '/leader-ranking',
    path: '/leader-ranking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderProceduresRoute =
  AuthenticatedLeaderProceduresRouteImport.update({
    id: '/leader-procedures',
    path: '/leader-procedures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderMapRoute = AuthenticatedLeaderMapRouteImport.update({
  id: '/leader-map',
  path: '/leader-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderConfigRoute =
  AuthenticatedLeaderConfigRouteImport.update({
    id: '/leader-config',
    path: '/leader-config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderRoute = AuthenticatedLeaderRouteImport.update({
  id: '/leader',
  path: '/leader',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftIdReportRoute =
  AuthenticatedShiftIdReportRouteImport.update({
    id: '/shift_/$id/report',
    path: '/shift/$id/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leader': typeof AuthenticatedLeaderRoute
  '/leader-config': typeof AuthenticatedLeaderConfigRoute
  '/leader-map': typeof AuthenticatedLeaderMapRoute
  '/leader-procedures': typeof AuthenticatedLeaderProceduresRoute
  '/leader-ranking': typeof AuthenticatedLeaderRankingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/variable': typeof AuthenticatedVariableRoute
  '/shift/$id/report': typeof AuthenticatedShiftIdReportRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leader': typeof AuthenticatedLeaderRoute
  '/leader-config': typeof AuthenticatedLeaderConfigRoute
  '/leader-map': typeof AuthenticatedLeaderMapRoute
  '/leader-procedures': typeof AuthenticatedLeaderProceduresRoute
  '/leader-ranking': typeof AuthenticatedLeaderRankingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/variable': typeof AuthenticatedVariableRoute
  '/': typeof AuthenticatedIndexRoute
  '/shift/$id/report': typeof AuthenticatedShiftIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/_authenticated/leader': typeof AuthenticatedLeaderRoute
  '/_authenticated/leader-config': typeof AuthenticatedLeaderConfigRoute
  '/_authenticated/leader-map': typeof AuthenticatedLeaderMapRoute
  '/_authenticated/leader-procedures': typeof AuthenticatedLeaderProceduresRoute
  '/_authenticated/leader-ranking': typeof AuthenticatedLeaderRankingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/productivity': typeof AuthenticatedProductivityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shift': typeof AuthenticatedShiftRoute
  '/_authenticated/variable': typeof AuthenticatedVariableRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/shift_/$id/report': typeof AuthenticatedShiftIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/leader'
    | '/leader-config'
    | '/leader-map'
    | '/leader-procedures'
    | '/leader-ranking'
    | '/onboarding'
    | '/productivity'
    | '/settings'
    | '/shift'
    | '/variable'
    | '/shift/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/leader'
    | '/leader-config'
    | '/leader-map'
    | '/leader-procedures'
    | '/leader-ranking'
    | '/onboarding'
    | '/productivity'
    | '/settings'
    | '/shift'
    | '/variable'
    | '/'
    | '/shift/$id/report'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/leader'
    | '/_authenticated/leader-config'
    | '/_authenticated/leader-map'
    | '/_authenticated/leader-procedures'
    | '/_authenticated/leader-ranking'
    | '/_authenticated/onboarding'
    | '/_authenticated/productivity'
    | '/_authenticated/settings'
    | '/_authenticated/shift'
    | '/_authenticated/variable'
    | '/_authenticated/'
    | '/_authenticated/shift_/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/variable': {
      id: '/_authenticated/variable'
      path: '/variable'
      fullPath: '/variable'
      preLoaderRoute: typeof AuthenticatedVariableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift': {
      id: '/_authenticated/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AuthenticatedShiftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity': {
      id: '/_authenticated/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof AuthenticatedProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader-ranking': {
      id: '/_authenticated/leader-ranking'
      path: '/leader-ranking'
      fullPath: '/leader-ranking'
      preLoaderRoute: typeof AuthenticatedLeaderRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader-procedures': {
      id: '/_authenticated/leader-procedures'
      path: '/leader-procedures'
      fullPath: '/leader-procedures'
      preLoaderRoute: typeof AuthenticatedLeaderProceduresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader-map': {
      id: '/_authenticated/leader-map'
      path: '/leader-map'
      fullPath: '/leader-map'
      preLoaderRoute: typeof AuthenticatedLeaderMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader-config': {
      id: '/_authenticated/leader-config'
      path: '/leader-config'
      fullPath: '/leader-config'
      preLoaderRoute: typeof AuthenticatedLeaderConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader': {
      id: '/_authenticated/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof AuthenticatedLeaderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift_/$id/report': {
      id: '/_authenticated/shift_/$id/report'
      path: '/shift/$id/report'
      fullPath: '/shift/$id/report'
      preLoaderRoute: typeof AuthenticatedShiftIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLeaderRoute: typeof AuthenticatedLeaderRoute
  AuthenticatedLeaderConfigRoute: typeof AuthenticatedLeaderConfigRoute
  AuthenticatedLeaderMapRoute: typeof AuthenticatedLeaderMapRoute
  AuthenticatedLeaderProceduresRoute: typeof AuthenticatedLeaderProceduresRoute
  AuthenticatedLeaderRankingRoute: typeof AuthenticatedLeaderRankingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProductivityRoute: typeof AuthenticatedProductivityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftRoute: typeof AuthenticatedShiftRoute
  AuthenticatedVariableRoute: typeof AuthenticatedVariableRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedShiftIdReportRoute: typeof AuthenticatedShiftIdReportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLeaderRoute: AuthenticatedLeaderRoute,
  AuthenticatedLeaderConfigRoute: AuthenticatedLeaderConfigRoute,
  AuthenticatedLeaderMapRoute: AuthenticatedLeaderMapRoute,
  AuthenticatedLeaderProceduresRoute: AuthenticatedLeaderProceduresRoute,
  AuthenticatedLeaderRankingRoute: AuthenticatedLeaderRankingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProductivityRoute: AuthenticatedProductivityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftRoute: AuthenticatedShiftRoute,
  AuthenticatedVariableRoute: AuthenticatedVariableRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedShiftIdReportRoute: AuthenticatedShiftIdReportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
